import "./globals.css"; 
import { ProfileProvider } from '../context/ProfileContext';  
import Footer from '../components/Footer';

export const metadata = {
  title: "SRS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <ProfileProvider>
          {children} 
         
        </ProfileProvider>
        <Footer/>
      </body>
    </html>
  );
}

